#define WINDOW_SIZE_X 1280
#define WINDOW_SIZE_Y 660

#define TILE_SECTION_POS_X 50
#define TILE_SECTION_POS_Y 50
#define TEXTURE_PICKER_SIZE 512
#define TEXTURE_PICKER_TILES_PER_ROW 10

#define NAVIGATION_BUTTON_SIZE 50

#define BUTTON_TYPE_TEXTURE_PICKER 't'
#define BUTTON_TYPE_NAVIGATION 'n'

#define PATH_TO_TILESET "assets/tileset/"
